-- =====================================================
-- Project: E-commerce Sales Analysis
-- Tool: SQL (MySQL)
-- Objective: Analyze sales transactions to identify
-- revenue trends, top customers, and product performance.
-- =====================================================


-- Create a new database for the e-commerce sales analysis project
CREATE DATABASE project_db;

-- Select the project database for use
USE project_db;

-- Create a table to store order transaction data
CREATE TABLE orders (
order_id INT,
user_id INT,
product_id INT,
category VARCHAR(100),
price FLOAT,
qty INT,
total_price FLOAT,
order_date DATETIME,
country VARCHAR(100),
customer_segment VARCHAR(100)
);

-- Preview the first 10 rows of the dataset to understand the structure
SELECT * FROM orders LIMIT 10;

-- Count the total number of records in the dataset
SELECT COUNT(*) FROM orders;

-- Identify all countries where orders were placed
SELECT DISTINCT country FROM orders;

-- Identify the different customer segments in the dataset
SELECT DISTINCT customer_segment FROM orders;

-- Calculate total revenue generated from all orders
SELECT SUM(total_price) AS total_revenue FROM orders;

-- Calculate the total number of orders
SELECT COUNT(order_id) AS total_orders FROM orders;

-- Calculate the average order value across all transactions
SELECT AVG(total_price) AS avg_order_value FROM orders;

-- Analyze revenue contribution by country
SELECT country, SUM(total_price) AS revenue 
FROM orders 
GROUP BY country 
ORDER BY revenue DESC;

-- Analyze revenue generated by each product category
SELECT category, SUM(total_price) AS revenue 
FROM orders 
GROUP BY category 
ORDER BY revenue DESC;

-- Evaluate performance of each customer segment based on revenue and order count
SELECT customer_segment, SUM(total_price) AS revenue, COUNT(order_id) AS total_orders 
FROM orders 
GROUP BY customer_segment 
ORDER BY revenue DESC;

-- Analyze monthly revenue trends over time
SELECT YEAR(order_date) AS year, MONTH(order_date) AS month, SUM(total_price) AS revenue 
FROM orders 
GROUP BY YEAR(order_date), MONTH(order_date) 
ORDER BY year, month;

-- Identify the top 10 products generating the highest revenue
SELECT product_id, SUM(total_price) AS revenue 
FROM orders 
GROUP BY product_id 
ORDER BY revenue DESC 
LIMIT 10;

-- Identify the top 10 customers based on total revenue contribution
SELECT user_id, SUM(total_price) AS total_revenue 
FROM orders 
GROUP BY user_id 
ORDER BY total_revenue DESC 
LIMIT 10;

-- Analyze revenue performance by product category
SELECT category, SUM(total_price) AS revenue 
FROM orders 
GROUP BY category 
ORDER BY revenue DESC;

-- Rank customers based on total revenue generated using a window function
SELECT user_id, SUM(total_price) AS revenue, 
RANK() OVER (ORDER BY SUM(total_price) DESC) AS revenue_rank 
FROM orders 
GROUP BY user_id;

-- Compare customer segments by total orders and revenue generated
SELECT customer_segment, COUNT(*) AS orders, SUM(total_price) AS revenue 
FROM orders 
GROUP BY customer_segment;

-- Calculate daily revenue to analyze short-term sales trends
SELECT DATE(order_date) AS order_day, SUM(total_price) AS revenue 
FROM orders 
GROUP BY order_day 
ORDER BY order_day;

-- Analyze revenue by both country and product category
SELECT country, category, SUM(total_price) AS revenue 
FROM orders 
GROUP BY country, category 
ORDER BY country, revenue DESC;

-- Compare average order value across different customer segments
SELECT customer_segment, AVG(total_price) AS avg_order_value 
FROM orders 
GROUP BY customer_segment;